kind: List
apiVersion: v1
items:

- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: nginx-rc
    namespace: dev
  spec:
    replicas: 2
    selector:
      app: nginx
      version: latest
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
          version: latest
      spec:
        containers:
          - name: nginx-rc-pods
            image: nginx
            imagePullPolicy: Always
            ports:
              - containerPort: 80
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 3
              timeoutSeconds: 3

- kind: Service
  apiVersion: v1
  metadata:
    name: nginx-service
    namespace: dev
    labels:
      app: nginx-service
  spec:
    type: NodePort
    ports:
      - port: 80
    selector:
      app: nginx
      version: latest
