---
- hosts: all
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Update /etc/hosts file
      template:
        src: etc_hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
