---
- hosts: all
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Update /etc/hosts file
      template:
        src:    templates/etc_hosts.j2
        dest:   /etc/hosts
        backup: yes
        owner:  root
        group:  root
        mode:   0644

- hosts: k8s
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Create Kubernetes repo
      template:
        src:    templates/kubernetes_repo.j2
        dest:   /etc/yum.repos.d/kubernetes.repo
        backup: yes
        owner:  root
        group:  root
        mode:   0644

- hosts: etcd_cluster
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Install ETCD package
      package:
        name:  "{{ item }}"
        state: present
      with_items:
        - etcd
    - name: Configure ETCD service
      template:
        src:    templates/etcd_conf.j2
        dest:   /etc/etcd/etcd.conf
        backup: yes
        owner:  root
        group:  root
        mode:   0644
      notify: Restart ETCD service
    - name: Enable ETCD service
      service:
        name:    etcd
        state:   running
        enabled: yes
  handlers:
    - name: Restart ETCD service
      service:
        name:  etcd
        state: restarted

- hosts: k8s_master
  vars_files:
    - external_variables.yaml
  # tasks:
  #   - name: 

- hosts: k8s_node
  vars_files:
    - external_variables.yaml
  # tasks:
  #   - name: 

- hosts: k8s_admin
  vars_files:
    - external_variables.yaml
  # tasks:
  #   - name: 