---
- hosts: all
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Update /etc/hosts file
      template:
        src:    templates/etc_hosts.j2
        dest:   /etc/hosts
        owner:  root
        group:  root
        mode:   0644

- hosts: k8s
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Create Kubernetes repo
      template:
        src:    templates/kubernetes_repo.j2
        dest:   /etc/yum.repos.d/kubernetes.repo
        owner:  root
        group:  root
        mode:   0644

- hosts: etcd
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Install ETCD package
      package:
        name:  "{{ item }}"
        state: present
      with_items:
        - etcd
    - name: Configure ETCD service
      template:
        src:    templates/etcd_conf.j2
        dest:   /etc/etcd/etcd.conf
        owner:  root
        group:  root
        mode:   0644
      notify: Restart ETCD service
    - name: Enable ETCD service
      service:
        name:    etcd
        state:   started
        enabled: yes
  handlers:
    - name: Restart ETCD service
      service:
        name:  etcd
        state: restarted

- hosts: k8s_master
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Ensure bridge-nf-call exists for K8s
      sysctl:
        name: "{{ item.option }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/bridge-nf-call.conf
      with_items:
        - option: net.bridge.bridge-nf-call-iptable
          value: 1
        - option: net.bridge.bridge-nf-call-ip6tables
          value: 1
        - option: net.bridge.bridge-nf-call-arptables
          value: 1
    - name: Install Docker packages
      package:
        name:  "{{ item }}"
        state: present
      with_items:
        - docker-1.12.6-16.el7.centos
    - name: Ensure Docker systemd directory exists
      file:
        path:   /etc/systemd/system/docker.service.d
        state:  directory
    - name: Configure Docker - systemd
      template:
        src:    templates/docker_service_d_50_http_proxy.j2
        dest:   /etc/systemd/system/docker.service.d/50-http-proxy.conf
        owner:  root
        group:  root
        mode:   0644
    - name: Configure Docker - sysconfig/docker
      template:
        src:    templates/docker_sysconfig_docker.j2
        dest:   /etc/sysconfig/docker
        owner:  root
        group:  root
        mode:   0644
    - name: Configure Docker - sysconfig//docker-storage-setup
      template:
        src:    templates/docker_sysconfig_docker_storage_setup.j2
        dest:   /etc/sysconfig/docker-storage-setup
        owner:  root
        group:  root
        mode:   0644
    - name: Enable Docker service
      service:
        name:    docker
        state:   started
        enabled: yes
    - name: Install K8s packages
      package:
        name:  "{{ item }}"
        state: present
      with_items:
        - kubelet-1.7.0
        - kubeadm-1.7.0
        - kubectl-1.7.0
        - kubernetes-cni-0.5.1
    - name: Enable K8s service
      service:
        name:    kubelet
        state:   started
        enabled: yes
    - name: Configure K8s - kubeadm
      template:
        src:    templates/kubeadm_config_yaml.j2
        dest:   /root/kubeadm-config.yaml
        owner:  root
        group:  root
        mode:   0644
    - name: Configure K8s - Calico
      template:
        src:    templates/calico_external_etcd_yaml.j2
        dest:   /root/calico-external-etcd.yaml
        owner:  root
        group:  root
        mode:   0644




  handlers:
    - name: Restart K8s service
      service:
        name:  kubelet
        state: restarted




- hosts: k8s_node
  vars_files:
    - external_variables.yaml
  # tasks:
  #   - name: 

- hosts: k8s_admin
  vars_files:
    - external_variables.yaml
  # tasks:
  #   - name: 