apiVersion: v1
kind: List
items:

- kind: Pod
  apiVersion: v1
  metadata:
    name: data
    labels:
      name: data
  spec:
    containers:
      - name: data
        image: docker-registry:5000/library/database:latest
        env:
          - name: TZ
            value: "America/Los_Angeles"
        ports:
          - name: mysql
            containerPort: 3306
        volumeMounts:
          - name: data-nfs-storage
            mountPath: "/home/www/mysql"
          - name: local-etc-localtime
            mountPath: "/etc/localtime"
            readOnly: true
    volumes:
      - name: data-nfs-storage
        nfs:
          server: 10.199.54.5
          path: "/nfs/exports/share0X"
      - name: local-etc-localtime
        hostPath:
          path: "/etc/localtime"

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      name: data
    name: data
  spec:
    ports:
      - port: 3306
        # targetPort: 3306
    selector:
      name: data
    # type: LoadBalancer
    # sessionAffinity: ClientIP
