apiVersion: v1
kind: List
items:

- kind: Service
  apiVersion: v1
  metadata:
    name: state04
  spec:
    ports:
      - port: 3306

- kind: Endpoints
  apiVersion: v1
  metadata:
    name: state04
  subsets:
  - addresses:
      - ip: 10.199.54.XXX
    ports:
      - port: 3306
        # targetPort: 3306
        protocol: TCP
      
