apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    name: web01
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30080   # node port
    port: 8001        # service port
    targetPort: 80    # pod port