kind: List
apiVersion: v1
items:

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: pv-5g-db-01
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /nfs/exports/share01
      server: 10.199.54.5

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: pv-3g-web-01
  spec:
    capacity:
      storage: 3Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /nfs/exports/share02
      server: 10.199.54.5
